<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://omni1.mobile-gw.com:9010/v1/omni/message");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\n\"channels\": [\n\n\"SMS\"\n\n],\n\n\"destinations\": [\n\n{\n\n\"phoneNumber\": \"385955541310\"\n\n}\n\n],\n\n\"sms\": {\n\n\"sender\": \"smssender\",\n\n\"text\": \"Sms text\"\n\n}\n\n}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Authorization: Basic aGVsaXhuZWJ1bGE6K0t7YEc9LWNgNEJ0bjtVWA==";
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
